# Generated by Django 2.2.1 on 2019-05-09 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20190509_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
